export const VIEW_ALL_ORDERS = "VIEW_ALL_ORDERS";
export const VIEW_SINGLE_ORDER = "VIEW_SINGLE_ORDER";
export const VIEW_ORDERS_BY_BUYER_CODE = "VIEW_ORDERS_BY_BUYER_CODE";
export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const DIST_COMPLETED_ORDERS = "DIST_COMPLETED_ORDERS";
export const GET_ALL_ORDERS_BY_DATE = "GET_ALL_ORDERS_BY_DATE";
